name: 'Dotnet build action'
description: 'cutsom dotnet action using github'
inputs: 
  command:
    description: 'follow the commands'
    required: true
    default: restore
runs:
  using: "composite"
  steps:
    - run: dotnet ${{ inputs.command }}
      shell: bash 
    
